In [7]:
import pandas as pd
import numpy as np
import time
from sklearn.preprocessing import StandardScaler
import pickle



In [13]:
dataset=pd.read_csv("Wine.csv")
X=dataset.iloc[:,0:13].values
Y=dataset.iloc[:,13].values

In [39]:
dataset

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [49]:
dataset["Customer_Segment"].value_counts()

Customer_Segment
2    71
1    59
3    48
Name: count, dtype: int64

In [27]:
#def split_scaler(X,Y)
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=0,test_size=0.25)
sc= StandardScaler()
X_train=sc.fit_transform( X_train)
X_test=sc.transform(X_test)

In [37]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)
explained_variance=pca.explained_variance_ratio_

In [75]:
#from sklearn.linear_model import LogisticRegression
#classifier=LogisticRegression(random_state=0)
#classifier.fit(X_train,Y_train)


LogisticRegression(random_state=0)

In [119]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(X_train,Y_train)

KNeighborsClassifier()

In [121]:
from sklearn.tree import DecisionTreeClassifier
DTC=DecisionTreeClassifier()
classifier.fit(X_train,Y_train)

KNeighborsClassifier()

In [107]:
y_pred=classifier.predict(X_test)

In [109]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred,Y_test)

In [111]:
cm

array([[16,  1,  0],
       [ 0, 20,  0],
       [ 0,  0,  8]], dtype=int64)

In [113]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_pred,Y_test)

In [115]:
print(clf_report) 

              precision    recall  f1-score   support

           1       1.00      0.94      0.97        17
           2       0.95      1.00      0.98        20
           3       1.00      1.00      1.00         8

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [ ]:
from svlearn.svm import svc

In [57]:
y_pred=classifier.predict(X_test)


In [59]:
y_pred

array([1, 3, 2, 1, 2, 1, 1, 3, 2, 2, 3, 3, 1, 2, 3, 2, 1, 1, 2, 1, 2, 1,
       1, 2, 2, 2, 2, 2, 2, 3, 1, 1, 2, 1, 1, 1, 3, 2, 2, 3, 1, 1, 2, 2,
       2], dtype=int64)

In [71]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred,Y_test)

In [77]:
cm

array([[16,  1,  0],
       [ 0, 20,  0],
       [ 0,  0,  8]], dtype=int64)

In [79]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_pred,Y_test)

In [83]:
print(clf_report)

              precision    recall  f1-score   support

           1       1.00      0.94      0.97        17
           2       0.95      1.00      0.98        20
           3       1.00      1.00      1.00         8

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

